# a function to generate filters by folders
function(MakeFilter)
   foreach(FILE ${ARGN})
   get_filename_component(PARENT_DIR "${FILE}" DIRECTORY)
   get_filename_component(FILE_EXT "${FILE}" DIRECTORY)
   string(REPLACE "${CMAKE_CURRENT_SOURCE_DIR}/" "" GROUP "${PARENT_DIR}")
   string(REPLACE "/" "\\" GROUP "${GROUP}")
   if ("${FILE_EXT}" MATCHES ".*\\.cpp")
      set(GROUP "Source Files\\${GROUP}")
   elseif("${FILE_EXT}" MATCHES ".*\\.c")
      set(GROUP "Source Files\\${GROUP}")
   elseif("${FILE_EXT}" MATCHES ".*\\.cxx")
      set(GROUP "Source Files\\${GROUP}")
   elseif("${FILE_EXT}" MATCHES ".*\\.h")
      set(GROUP "Header Files\\${GROUP}")
   elseif("${FILE_EXT}" MATCHES ".*\\.mm")
      set(GROUP "Source Files\\${GROUP}")
   endif()
   source_group("${GROUP}" FILES "${FILE}")
   endforeach()
endfunction(MakeFilter)